~~NOCACHE~~
[[category:autor| ]]
[[daneOsobowe:={{ author }}| ]]
====={{ author }}=====

====Problems proposed====
{{ '{{' -}}
#ask: [[category:problem]] [[maAutora::autor:{{ author | str2doku }}]] |
    ?nazwa |
    sort=nazwa |
    default=No problems proposed
}}

====Problems solved====
{{ '{{' -}}
#ask: [[category:rozwiazanie]] [[maAutora::autor:{{ author | str2doku }}]] |
    ?nazwa |
    sort=nazwa |
    default=No problems solved
}}